Apakah $\begin{bmatrix}1 \\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? Jika iya, berapakah eigenvalue-nya?


# Jawaban

## Analisa manual:

### Mencari eigenvalue

$A = \begin{bmatrix} 1 & -1 \\ 6 & -4 \end{bmatrix}$

$det(A - \lambda I) = 0$

$det(\begin{bmatrix} 1 & -1 \\ 6 & -4 \end{bmatrix} - \begin{bmatrix}\lambda & 0 \\ 0 & \lambda \end{bmatrix}) = 0$

$det(\begin{bmatrix} 1 - \lambda & -1 \\ 6 & -4 - \lambda \end{bmatrix}) = 0$

$(1 - \lambda)(-4 - \lambda) - (-1)(6) = 0$

$(-4 + 3 \lambda + \lambda^{2}) - (-6) = 0$

$\lambda^{2} + 3 \lambda + 2 = 0$

$(\lambda + 1)(\lambda + 2) = 0$

Eigenvalue untuk matriks A adalah $\lambda = -1$ dan $\lambda = -2$

### Mencari eigenvector untuk masing-masing eigenvalue

#### $\lambda = -1$

$\begin{bmatrix} 1 - \lambda & -1 \\ 6 & -4 - \lambda \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 1 - (-1) & -1 \\ 6 & -4 - (-1) \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 2 & -1 \\ 6 & -3 \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 2x_{1} - x_{2} \\ 6x_{1} - 3x_{2} \end{bmatrix} = 0$

$2x_{1} - x_{2} = 0$

$2x_{1} = x_{2}$

$6x_{1} - 3x_{2} = 0$

$6x_{1} = 3x_{2}$

$3(2x_{1}) = 3(x_{2})$

$\begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} x_{1} \\ 2x_{1} \end{bmatrix}$

$\begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$

#### $\lambda = -2$

$\begin{bmatrix} 1 - \lambda & -1 \\ 6 & -4 - \lambda \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 1 - (-2) & -1 \\ 6 & -4 - (-2) \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 3 & -1 \\ 6 & -2 \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = 0$

$\begin{bmatrix} 3x_{1} - x_{2} \\ 6x_{1} - 2x_{2} \end{bmatrix} = 0$

$3x_{1} - x_{2} = 0$

$3x_{1} = x_{2}$

$6x_{1} - 2x_{2} = 0$

$6x_{1} = 2x_{2}$

$2(3x_{1}) = 2(x_{2})$

$\begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} x_{1} \\ 3x_{1} \end{bmatrix}$

$\begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} 1 \\ 3 \end{bmatrix}$

### Kesimpulan Analisa Manual:

$\begin{bmatrix} 1 \\ 3 \end{bmatrix}$ merupakan eigenvector dari $\begin{bmatrix} 1 & -1 \\ 6 & -4 \end{bmatrix}$ yang berkorespondensi dengan eigenvalue sebesar $\lambda = -2$

## Analisa program:

Muat *library* numpy:

In [17]:
import numpy as np

Definisikan matriks A:

In [20]:
A = np.array([[1, -1],
            [6, -4]])

A

array([[ 1, -1],
       [ 6, -4]])

Gunakan perintah `np.linalg.eig()` untuk mendapatkan eigenvalue dan eigenvector dari matriks A:

In [21]:
A_eval, A_evec = np.linalg.eig(A)

Eigenvalue untuk matriks A:

In [23]:
A_eval

array([-1., -2.])

Eigenvector untuk matriks A:

In [24]:
A_evec

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [30]:
A_evec * np.linalg.norm(A_evec)

array([[0.63245553, 0.4472136 ],
       [1.26491106, 1.34164079]])