In [1]:
import numpy as np

- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [2]:
T = np.array([[[23, 50], [7, 12]],
            [[57, 67], [99, 43]],
            [[75, 21], [57, 12]],
            [[87, 26], [18, 84]]])

T

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [7]:
A = np.array([[23, 50, 19],
            [7, 12, 109],
            [57, 67, 98]])

B = np.array([[17],
            [22],
            [19]])

C = A @ B

C

array([[1852],
       [2454],
       [4305]])

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [8]:
# Panggil matriks A karena sama seperti soal di atas

A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [10]:
# Transpos matriks A

A_trans = A.T

A_trans

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [15]:
# Menghitung determinan A

A_det = np.linalg.det(A)

A_det

131344.0000000002

In [16]:
# Membuat matriks A invers

A_inv = np.linalg.inv(A)

A_inv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])