# Matriks

In [50]:
# Load library numpy untuk melakukan penulisan matriks

import numpy as np

Matriks merupakan sebuah *array* dua dimensi yang terdiri dari baris dan kolom. Matriks dalam *array* dapat didefinisikan sebagai berikut:

In [51]:
A = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

A

# Variabel matriks nantinya ditandai menggunakan huruf kapital

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
A[1]

array([4, 5, 6])

In [53]:
A[:, 2]

array([3, 6, 9])

In [54]:
A[2, 1:]

array([8, 9])

Berikut adalah tipe-tipe khusus dari matriks:

In [55]:
# Matriks persegi (m,m)

X = np.array([[4, 9, 2],
            [3, 5, 7],
            [2, 7, 6]])

X

array([[4, 9, 2],
       [3, 5, 7],
       [2, 7, 6]])

In [56]:
# Matriks segitiga atas

np.triu(X)

array([[4, 9, 2],
       [0, 5, 7],
       [0, 0, 6]])

In [57]:
# Matriks segitiga bawah

np.tril(X)

array([[4, 0, 0],
       [3, 5, 0],
       [2, 7, 6]])

In [58]:
# Matriks diagonal

np.diag(X)

array([4, 5, 6])

In [59]:
# Membuat matriks identitas

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Sama seperti pada vektor, matriks pun dapat dioperasikan secara aritmatika:

In [60]:
B = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Penjumlahan:

In [61]:
# Skalar -> Matriks

A + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
# Matriks -> Matriks (dimensi sama)

A + B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [63]:
# Matriks -> Matriks (dimensi berbeda)

b = np.array([[1, 2, 3]])

A + b

# Hanya dapat dilakukan ketika jumlah kolomnya sama

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

Pengurangan:

In [64]:
# Skalar -> Matriks

A - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [65]:
# Matriks -> Matriks (dimensi sama)

A - B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
# Matriks -> Matriks (dimensi berbeda)

A - b

# Hanya dapat dilakukan ketika jumlah kolomnya sama

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

Pembagian:

In [67]:
# Skalar -> Matriks

A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [68]:
# Matriks -> Matriks (dimensi sama)

A / B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
# Matriks -> Matriks (dimensi berbeda)

A / b

# Hanya dapat dilakukan ketika jumlah kolomnya sama

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

Perkalian:

In [70]:
# Skalar -> Matriks

A * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [71]:
# Hadamard Product (Element-wise)

A * B

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [72]:
# Dot-product (sum of multiplication)

A @ B

# Untuk matriks yang dimensinya berbeda, selama kolom pada A sama dengan baris pada B, tetap dapat dilakukan
# Perkalian tersebut akan menghasilkan matriks baru dengan jumlah baris matriks A dan jumlah kolom matriks B

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Transpos matriks:

In [73]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Invers matriks:

In [85]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
A_inv = np.linalg.inv(A)

A_inv

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [87]:
A @ A_inv

array([[ 0.,  0.,  0.],
       [-4.,  0., -4.],
       [ 0.,  0.,  0.]])

Determinan matriks:

In [80]:
A_det = np.linalg.det(A)

A_det

6.66133814775094e-16

Tensor merupakan generalisasi dari vektor dan matriks. Tensor merupakan *array* yang memiliki banyak dimensi.